create database pizzasproject;
use pizzasproject;
select * from pizza_sales;
-- total revenue generated by pizzas 
SELECT 
    ROUND(SUM(total_price), 0) AS total_revenue
FROM
    pizza_sales;
    
-- average revenue per order 
SELECT 
    ROUND(SUM(total_price) / COUNT(DISTINCT order_id),
            1) AS avg_order_value
FROM
    pizza_sales;

-- Total Number of Pizza sold
SELECT 
    SUM(quantity) AS totalqty
FROM
    pizza_sales;



-- average pizza per order 
SELECT 
    SUM(quantity) / COUNT(DISTINCT order_id) avg_pizza_per_order
FROM
    pizza_sales;


-- Revenue by weekdays of pizza
SELECT 
    DAYNAME(STR_TO_DATE(order_date, '%Y-%m-%d')) weekdays,
    CAST(SUM(total_price) AS DECIMAL (10 , 2 )) as revenue
FROM
    pizza_sales
GROUP BY DAYNAME(STR_TO_DATE(order_date, '%Y-%m-%d'));

-- Revenue by month of pizza
SELECT 
    MONTHNAME(STR_TO_DATE(order_date, '%Y-%m-%d')) Month,
    CAST(SUM(total_price) AS DECIMAL (10 , 2 )) as Revenue
FROM
    pizza_sales
GROUP BY MONTHNAME(STR_TO_DATE(order_date, '%Y-%m-%d'));


-- Total orders By  Weekdays
SELECT 
    DAYNAME(STR_TO_DATE(order_date, '%Y-%m-%d')) day_name,
    COUNT(DISTINCT order_id) AS total_orders
FROM
    pizza_sales
GROUP BY DAYNAME(STR_TO_DATE(order_date, '%Y-%m-%d'));

-- total orders according to month
SELECT 
    MONTHNAME(STR_TO_DATE(order_date, '%Y-%m-%d')) month_name,
    COUNT(DISTINCT order_id) AS total_orders
FROM
    pizza_sales
GROUP BY MONTHNAME(STR_TO_DATE(order_date, '%Y-%m-%d'))
ORDER BY total_orders DESC;


-- percentage of sales over pizza category
SELECT 
    pizza_category , (SUM(total_price))*100 / (SELECT 
            SUM(total_price)
        FROM
            pizza_sales) as total_sales_percentage
FROM
    pizza_sales
    
GROUP BY pizza_category;

-- percentage over pizza size by revenue

SELECT 
    pizza_size , round((SUM(total_price))*100 / (SELECT 
            SUM(total_price)
        FROM
            pizza_sales),2) as total_sales_percentage
FROM
    pizza_sales
GROUP BY pizza_size;
-- top 5 pizza according to sales
select  pizza_name,sum(total_price) totalSales
from pizza_sales
group by pizza_name order by sum(total_price) desc limit 5;



-- bottom 5 pizza by sales 
select  pizza_name,sum(total_price) totalSales
from pizza_sales
group by pizza_name order by sum(total_price) asc limit 5;


-- top 5 pizza according to quantity
select  pizza_name,sum(quantity) totalSales
from pizza_sales
group by pizza_name order by sum(quantity) desc limit 5;


-- bottom 5 pizza according to quantity
SELECT 
    pizza_name, SUM(quantity) totalSales
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY SUM(quantity) ASC
LIMIT 5;
select * from pizza_sales;
SELECT order_id,order_date
FROM pizza_sales
WHERE STR_TO_DATE(order_date, '%Y-%m-%d') >= DATE_SUB(
    (SELECT MAX(STR_TO_DATE(order_date, '%Y-%m-%d')) FROM pizza_sales), 
    INTERVAL 6 MONTH
);
